# Generated by Django 4.1.5 on 2023-03-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_conference_payment_time_and_date_person_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='venue_photo',
            field=models.ImageField(default=True, null=True, upload_to='photo'),
        ),
    ]
