# Generated by Django 4.1.5 on 2023-05-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_password_person_ph_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
