# Generated by Django 4.1.5 on 2023-05-24 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_payment_ending_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='conference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.conference'),
        ),
    ]
