# Generated by Django 4.1.5 on 2023-05-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_payment_conference'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='payment_status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='payment',
        ),
    ]
