# Generated by Django 4.1.5 on 2023-02-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=100)),
                ('venue_state', models.CharField(max_length=100)),
                ('venue_city', models.CharField(max_length=100)),
                ('venue_photo', models.CharField(max_length=100)),
                ('venue_booking_price', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('food', models.CharField(max_length=100)),
                ('props', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cvv', models.IntegerField()),
                ('card_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Time_and_Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_time', models.TimeField()),
                ('ending_time', models.TimeField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='usertype',
            field=models.CharField(default=7, max_length=50),
            preserve_default=False,
        ),
    ]
