# Generated by Django 4.1.5 on 2023-05-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_payment_conference'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
