# Generated by Django 4.1.5 on 2023-05-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_conference_is_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='conference',
        ),
        migrations.AlterField(
            model_name='payment',
            name='ending_time',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='starting_time',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
