# Generated by Django 4.1.5 on 2023-05-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_payment_conference_alter_payment_ending_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='ending_time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='starting_time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
