# Generated by Django 4.1.5 on 2023-05-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_remove_conference_payment_status_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='ending_time',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='starting_time',
        ),
        migrations.AddField(
            model_name='conference',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='ending_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='starting_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
