# Generated by Django 4.1.5 on 2023-05-26 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_user_pro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_pro',
        ),
    ]
