# Generated by Django 4.1.5 on 2023-05-27 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
